services:
  web:
    build: .
    ports:
      - "5005:5000"
    volumes:
      - .:/app
  #   depends_on:
  #     - db
  # db:
  #   image: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data